### ISSUE TITLE
Almost all assets are served over http 1 not http2 on local

### ISSUE THREAD

**Issue by Salomari1987** [ledermann/templatus-hotwire#58]
Hello Georg,

I've setup the project as described in the README both locally using puma-dev and on docker, however my assets still get served over http 1. I opened your demo app, and I notice it gets served over the h2 protocol. I am new to rails in general but I was just wondering of we need a production deployment to enable h2 protocol or am I missing something?
<img width="1026" alt="Screen Shot 2022-01-10 at 6 30 49 PM" src="https://user-images.githubusercontent.com/19625384/148802019-42073776-5d8f-4949-abe8-557b8a27ec3a.png">

**Comment by ledermann** [comment]
Thanks for your interest in this project :)

Yes, my demo installation runs behind a reverse proxy which handles all the HTTP/2 stuff. I use Traefik, but there are lots of other options. Puma does not support it yet. So, when you run the Docker setup locally, there will be just HTTP/1.1.

**Comment by Salomari1987** [comment]
Awesome thank you
